services:
  prasorganic-vault:
    container_name: prasorganic-vault
    image: hashicorp/vault:1.17
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
    ports:
      - 8200:8200

    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-listen-address='0.0.0.0:8200' -dev-root-token-id='root'